2023-07-05 11:28:35,759 (14743/MainThread) duckcli.main ERROR - sql: 'select * from read_csv("https://data.urbansharing.com/oslobysykkel.no/trips/v1/2023/07.csv")', error: Exception('Not connected to database.')
2023-07-05 11:28:35,760 (14743/MainThread) duckcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/andrejakobsen/opt/miniconda3/lib/python3.9/site-packages/duckcli/main.py", line 438, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/andrejakobsen/opt/miniconda3/lib/python3.9/site-packages/duckcli/sqlexecute.py", line 106, in run\n    raise Exception("Not connected to database.")\nException: Not connected to database.\n'
2023-07-05 11:29:29,107 (14743/MainThread) duckcli.main ERROR - sql: "select * from read_csv_auto('https://data.urbansharing.com/oslobysykkel.no/trips/v1/2023/07.csv')", error: Exception('Not connected to database.')
2023-07-05 11:29:29,107 (14743/MainThread) duckcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/andrejakobsen/opt/miniconda3/lib/python3.9/site-packages/duckcli/main.py", line 438, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/andrejakobsen/opt/miniconda3/lib/python3.9/site-packages/duckcli/sqlexecute.py", line 106, in run\n    raise Exception("Not connected to database.")\nException: Not connected to database.\n'
